version: '3'

services:

  web:
    image: python:3.10.12
    command: bash -c "pip install -r /app/requirements.txt && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

